### ISSUE TITLE
CI with netlify and travis

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#2]

**Comment by jeroen** [comment]
What do you need netlify for exactly? FYI if you create a `gh-pages` branch in this repository it will be availalbe via https://ropenscilabs.github.io/drake-manual

**Comment by wlandau** [comment]
I was thinking it would be a convenient way to preview incoming PRs. For example, I checked https://deploy-preview-184--ropensci.netlify.com/ when I was working on https://github.com/ropensci/roweb2/pull/184.

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/ropenscilabs/drake-manual/pull/10#issuecomment-401561178

**Comment by lorenzwalthert** [comment]
I just published my fork here: https://trusting-booth-33c1e2.netlify.com

You can do it with these steps: 

1. go to travis and add add drake-manual repo.
2. install [netlifyctl](https://github.com/netlify/netlifyctl).
3. deploy the book from your local machine `$ netlifyctl deploy` (select new site, select 
  _book as the directory to deploy) and change deployment URL on netlify.com.
4. get API token from Netlify [here](https://app.netlify.com/account/applications) and add as environment variable NETLIFYKEY in travis (as hidden).
5. merge this PR.
6. remove all HTML from the git history with filter branch (and force push), e.g. as explained [here](https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history). I think force push is justified since the repo is very young and has no forks (apart from mine).

**Comment by wlandau** [comment]
I just did steps 1-3. I think we may also need ropenscilabs to allow netlify integration. cc @maelle.

**Comment by sckott** [comment]
@wlandau i've not used netlify with tokens, so not sure of what's needed. Can you create a token when you login to netlify?

**Comment by wlandau** [comment]
I can, and I am in the process of figuring out how to use it. I have never done this before either.

**Comment by lorenzwalthert** [comment]
Sorry I did not provide a more detailed explanation. Here you go:
To get the token, you first the have to sign up with Netlify and then click on the link I provided above under step 4 (https://app.netlify.com/account/applications). Then, copy the token you just created on Netlify to your clipboard. Next, you log in to Travis where you add the drake-manual repository from GitHub if you have not done that already. Then, go to **more options** -> **settings** of the [repository](https://travis-ci.org/ropenscilabs/drake-manual) (top right button), scroll down to Environment Variables
and add a new environment variable `NETLIFYKEY` and paste the access token from your clipboard. Send me an email if you want me to help you with this on skype. It's simple but hard to explain in plain text.

**Comment by wlandau** [comment]
Thanks for elaborating, Lorenz. Those steps seem to have gone smoothly. At the very least, I see [Travis is setting the `NETLIFYKEY` variable](https://travis-ci.org/ropenscilabs/drake-manual/builds/400600998#L914).

I think one of the next steps is to figure out why [`deploy.sh`](https://github.com/ropenscilabs/drake-manual/blob/master/deploy.sh) is [not pushing new commits](https://travis-ci.org/ropenscilabs/drake-manual/builds/400600998#L2777) to [gh-pages](https://github.com/ropenscilabs/drake-manual/tree/gh-pages) and why Netlify is missing from GitHub status checks posted alongside each commit.

Another question: why is it necessary to remove all the HTML from the full commit history?

**Comment by lorenzwalthert** [comment]
It's a bit more complicated now since graph is no longer on cran so the installation of drake on my fork fails on travis. I suggest to postpone this until the next release of drake. We could also use the devel version of drake for now (or even in general?) using `usethis::use_devel_package("drake") to modify DESCRIPTION. What do you prefer?
Anyways, you can have a look at my [fork](https://travis-ci.org/lorenzwalthert/drake-manual/builds/400745965?utm_source=github_status&utm_medium=notification) - it should work once we can install drake. See also commit messages of the last few commits in the fork. I can provide more explanation if necessary, but I suggest to first resolve the instalation issue.

**Comment by lorenzwalthert** [comment]
> Another question: why is it necessary to remove all the HTML from the full commit history?

It's not strictly necessary but it makes the repo more lightweight. Also, maybe there was a misundertanding because I did not think of using Github Pages, I just used netlify so far, but if you want thepage to appear on https://ropenscilabs.github.io/drake-manual/, you are right that we need to push from travis to GitHub. Also, in the tic package of ropensci, there is a bookdown deployment functionality we could use, there is even an [example repo](https://github.com/krlmlr/tic.bookdown).

**Comment by lorenzwalthert** [comment]
See #15 for a version that I think should work, sorry about the ENV variable, it's NETLIFYKEY, not NETLIFY_PATH, or in other words, the variable from your screenshot has to be the variable in the script, so they have the same name.

**Comment by lorenzwalthert** [comment]
As far as `deploy.sh` goes: I think it's beause you don't specify in the `.travis.yaml`, similar to this:
https://github.com/lorenzwalthert/blogdown-cactus/blob/master/.travis.yml#L20-L21

**Comment by lorenzwalthert** [comment]
Also if you wanted to use GitHub pages (and hence commit html) we don't need netlify. If we use netlify, we don't need GitHub pages. What I did for my blog that I hosted on GitHub Pages was that I added a CNAME there to redirect from lorenzwalthert.github.io to lorenzwalthert.netlify.com. Sorry for all the confusion.

**Comment by wlandau** [comment]
Successfully deploying from Travis to the `gh-pages` branch in 21db5d088f502351d62036eef9d513948db163e7. Went back to my first approach: the `.travis.yml` and `_deploy.sh` files from https://github.com/rstudio/bookdown-demo. My earlier mistake with that was, of course, with GitHub personal access tokens. I needed a `GITHUB_PAT` with "repo" permissions.

![token1](https://user-images.githubusercontent.com/1580860/42412272-0332c1a2-81d7-11e8-9ed4-67f61ecd7647.png)

And for the auto-generated FAQ, I also needed a `GITHUB_TOKEN` to make sure I did not get kicked out of the REST API.

![token2](https://user-images.githubusercontent.com/1580860/42412285-55b60736-81d7-11e8-8ae9-982005a90620.png)

Finally, as Lorenz said, I needed to go into the travis-ci.org repo settings of `drake-manual` and add these tokens as environment variables `GITHUB_PAT` and `GITHUB_TOKEN`.

![env](https://user-images.githubusercontent.com/1580860/42412296-9b69f81e-81d7-11e8-9dbb-017e3b2fc902.png)

Then when I committed and pushed, Travis had access to `GITHUB_PAT` and `GITHUB_TOKEN` as ordinary shell variables (e.g. `GITHUB_PAT` in [`deploy.sh`](https://github.com/ropenscilabs/drake-manual/blob/master/deploy.sh))

As for Netlify, I do not think it is worth it. Pull request previews are not available for the version of the website that Travis builds. If they are ever available, I will reconsider.

Thanks for all your help everyone, especially Lorenz!

**Comment by lorenzwalthert** [comment]
Thank you. The previews are available if you use the draft mode. I implemented it for my blog, see  https://lorenzwalthert.netlify.com/posts/getting-up-and-running-with-blogdown-netlify-and-travis/ for an explanation. But there were some problems associated with it, although it should work in principle.

**Comment by lorenzwalthert** [comment]
The other approach would be to be to netlify for previews only (to some UR we don't care) and then use GitHub pages for the master deployment as it's implemented now. So netlify would build all your PRs but in the end, when merged, a Travis -> GitHub Pages build handles the deployment.

**Comment by wlandau** [comment]
> The other approach would be to be to netlify for previews only (to some UR we don't care) and then use GitHub pages for the master deployment as it's implemented now. So netlify would build all your PRs but in the end, when merged, a Travis -> GitHub Pages build handles the deployment.

Sounds perfect! I won't have time to work on this myself for a while, but I could certainly merge a PR quickly.

**Comment by wlandau** [comment]
Wait a minute: could a malicious PR deploy to `gh-pages` from a Travis build? I am starting to worry about this because #27 accidentally did it with a broken [`deploy.sh`](https://github.com/ropenscilabs/drake-manual/blob/master/deploy.sh). Maybe we should just use Netlify.

**Comment by wlandau** [comment]
From the [Travis docs](https://docs.travis-ci.com/user/environment-variables/), environment variables defined in the repository settings are not automatically available to forks. That means external pull requests will not see `GITHUB_PAT` and will not be published Travis. So it looks like we're fine on security.
