### ISSUE TITLE
Try Netlfiy again

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#71]
For PR previews only. See [`mlr`](https://github.com/mlr-org/mlr). Thanks @pat-s for the pointer.

**Comment by pat-s** [comment]
We are doing this via _tic_. Happy to help out if you want. I am one of the authors of _tic_ so if you do not want to fiddle with it, let me know 🙂

**Comment by wlandau** [comment]
Awesome! I would love help on this.

**Comment by pat-s** [comment]
FYI, I added a brief section about how to do this on the [mlr3 wiki](https://github.com/mlr-org/mlr3/wiki/CI-Guide#preview-of-docs-in-pull-requests) some time ago. 

Maybe that gets you going. This can only be done with full admin rights to a repo and just granting those to me for this part seems unnecessary.

**Comment by wlandau** [comment]
Point (4) at https://github.com/mlr-org/mlr3/wiki/CI-Guide#preview-of-docs-in-pull-requests seems to clash with the current approach:

1. Push the manual's source without a `docs/` folder.
2. Let Travis do the rest:
    1. Render the manual to `docs/`.
    2. Push the contents of `docs/` to the `gh-pages` branch.

I like building `docs/` on Travis because it takes less time and fewer local dependencies, and it is more reproducible. Is there a way to tell Netlify to wait for a new `docs/` folder to appear?

**Comment by pat-s** [comment]
> Let Travis do the rest:
> 
>     Render the manual to docs/.
>     Push the contents of docs/ to the gh-pages branch.
> 

I think there is some misunderstanding.

If you want to have a Netlify preview, the rendered version needs to live in `docs/` in master and not in gh-pages.

This is what is meant with `"Publish directory = docs"`.
Netlify renders from master `docs/` OR (if a PR) from the `docs/` of the respective PR.
This way Netlify is able to render a preview of the PR.

So to do it like that, you need to push the rendered content to master `docs/` instead of gh-pages during the CI build.

**Comment by wlandau** [comment]
Ah well, I guess it cannot be helped. I would rather not have to push `docs/`. Probably won't convert to `tic` because the infrastructure is already in place, but I plan to try `tic` for a new `bookdown` project at some point.
